In [1]:
!pip install ucimlrepo

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: pandas>=1.0.0 in c:\users\mails\appdata\roaming\python\python313\site-packages (from ucimlrepo) (2.3.3)
Requirement already satisfied: certifi>=2020.12.5 in c:\users\mails\appdata\roaming\python\python313\site-packages (from ucimlrepo) (2026.4.22)
Requirement already satisfied: numpy>=1.26.0 in c:\users\mails\appdata\roaming\python\python313\site-packages (from pandas>=1.0.0->ucimlrepo) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mails\appdata\roaming\python\python313\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mails\appdata\roaming\python\python313\site-packages (from pandas>=1.0.0->ucimlrepo) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mails\appdata\roaming\python\python313\site-packages (from pandas>=1.0.0->ucimlrepo) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\mails\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
metro_interstate_traffic_volume = fetch_ucirepo(id=492) 
  
# data (as pandas dataframes) 
X = metro_interstate_traffic_volume.data.features 
y = metro_interstate_traffic_volume.data.targets 
  
# metadata 
print(metro_interstate_traffic_volume.metadata) 
  
# variable information 
print(metro_interstate_traffic_volume.variables)

{'uci_id': 492, 'name': 'Metro Interstate Traffic Volume', 'repository_url': 'https://archive.ics.uci.edu/dataset/492/metro+interstate+traffic+volume', 'data_url': 'https://archive.ics.uci.edu/static/public/492/data.csv', 'abstract': 'Hourly Minneapolis-St Paul, MN traffic volume for westbound I-94. Includes weather and holiday features from 2012-2018.', 'area': 'Other', 'tasks': ['Regression'], 'characteristics': ['Multivariate', 'Sequential', 'Time-Series'], 'num_instances': 48204, 'num_features': 8, 'feature_types': ['Integer', 'Real'], 'demographics': [], 'target_col': ['traffic_volume'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2019, 'last_updated': 'Fri Mar 15 2024', 'dataset_doi': '10.24432/C5X60B', 'creators': ['John Hogue'], 'intro_paper': None, 'additional_info': {'summary': 'Hourly Interstate 94 Westbound traffic volume for MN DoT ATR station 301, roughly midway between Minneapolis and St Paul, MN. Hourly weather features and holidays included for impacts on traffic volume.', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'holiday                Categorical    US National holidays plus regional holiday, Minnesota State Fair\r\ntemp                   Numeric        Average temp in kelvin\r\nrain_1h                Numeric        Amount in mm of rain that occurred in the hour\r\nsnow_1h                Numeric        Amount in mm of snow that occurred in the hour\r\nclouds_all             Numeric        Percentage of cloud cover\r\nweather_main           Categorical    Short textual description of the current weather\r\nweather_description    Categorical    Longer textual description of the current weather\r\ndate_time              DateTime       Hour of the data collected in local CST time\r\ntraffic_volume         Numeric        Hourly I-94 ATR 301 reported westbound traffic volume', 'citation': None}}
                  name     role         type demographic  \
0              holiday  Feature  Categorical        None
1                 temp  Feature   Continuous        None
2              rain_1h  Feature   Continuous        None
3              snow_1h  Feature   Continuous        None
4           clouds_all  Feature      Integer        None
5         weather_main  Feature  Categorical        None
6  weather_description  Feature  Categorical        None
7            date_time  Feature         Date        None
8       traffic_volume   Target      Integer        None

                                         description   units missing_values
0  US National holidays plus regional holiday, Mi...    None             no
1                             Average temp in kelvin  Kelvin             no
2     Amount in mm of rain that occurred in the hour      mm             no
3     Amount in mm of snow that occurred in the hour      mm             no
4                          Percentage of cloud cover       %             no
5   Short textual description of the current weather    None             no
6  Longer textual description of the current weather    None             no
7       Hour of the data collected in local CST time    None             no
8  Hourly I-94 ATR 301 reported westbound traffic...    None             no

In [4]:
X.head()

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time
0,NaN,288.28,0.0,0.0,40,Clouds,scattered clouds,2012-10-02 09:00:00
1,NaN,289.36,0.0,0.0,75,Clouds,broken clouds,2012-10-02 10:00:00
2,NaN,289.58,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 11:00:00
3,NaN,290.13,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 12:00:00
4,NaN,291.14,0.0,0.0,75,Clouds,broken clouds,2012-10-02 13:00:00

In [5]:
X.tail()

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time
48199,NaN,283.45,0.0,0.0,75,Clouds,broken clouds,2018-09-30 19:00:00
48200,NaN,282.76,0.0,0.0,90,Clouds,overcast clouds,2018-09-30 20:00:00
48201,NaN,282.73,0.0,0.0,90,Thunderstorm,proximity thunderstorm,2018-09-30 21:00:00
48202,NaN,282.09,0.0,0.0,90,Clouds,overcast clouds,2018-09-30 22:00:00
48203,NaN,282.12,0.0,0.0,90,Clouds,overcast clouds,2018-09-30 23:00:00

In [7]:
y.head()

   traffic_volume
0            5545
1            4516
2            4767
3            5026
4            4918

In [8]:
y.tail()

       traffic_volume
48199            3543
48200            2781
48201            2159
48202            1450
48203             954